# Generated by Django 3.2 on 2022-05-07 20:05

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(default='000.000.000-00', max_length=14, unique=True, verbose_name='cpf')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da Eleição')),
                ('data_inicial', models.DateField(verbose_name='Data Inicial')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('candidatos', models.ManyToManyField(to='eleicao.Candidato')),
            ],
        ),
    ]
