# Generated by Django 3.2 on 2022-05-12 11:59

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='candidatos',
            field=models.ManyToManyField(blank=True, to='eleicao.Candidato'),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='nome',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nome da Eleição'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleitor', cpf_field.models.CPFField(default='000.000.000-00', max_length=14, verbose_name='cpf')),
                ('candidato', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eleicao.candidato')),
                ('pleito', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eleicao.eleicao')),
            ],
        ),
    ]
